### ISSUE TITLE
pip install -r resources.txt

### ISSUE THREAD

**Issue by jkhartshorne** [FormosanBank/FormosanBank#14]
This keeps failing for me. I tried a fresh virtual environment but got the same error:

(The full error is too long for my terminal and even what's in my terminal is too long for a github issue. Here's the tail end.)

>       Possible solutions:
>           1. Declare '__pyx_fuse_1dual_swap' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on '__pyx_fuse_1dual_swap' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:178:29: Exception check after calling 'reset_wscale' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare 'reset_wscale' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on 'reset_wscale' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:183:17: Exception check after calling '__pyx_fuse_1_axpy' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare '__pyx_fuse_1_axpy' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on '__pyx_fuse_1_axpy' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:185:17: Exception check after calling '__pyx_fuse_1_scal' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare '__pyx_fuse_1_scal' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on '__pyx_fuse_1_scal' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:189:13: Exception check after calling '__pyx_fuse_1_scal' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare '__pyx_fuse_1_scal' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on '__pyx_fuse_1_scal' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:351:29: Exception check after calling 'reset_wscale' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare 'reset_wscale' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on 'reset_wscale' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:356:17: Exception check after calling '__pyx_fuse_0_axpy' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare '__pyx_fuse_0_axpy' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on '__pyx_fuse_0_axpy' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:358:17: Exception check after calling '__pyx_fuse_0_scal' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare '__pyx_fuse_0_scal' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on '__pyx_fuse_0_scal' to allow an error code to be returned.
>       performance hint: sklearn/utils/_weight_vector.pyx:362:13: Exception check after calling '__pyx_fuse_0_scal' will always require the GIL to be acquired.
>       Possible solutions:
>           1. Declare '__pyx_fuse_0_scal' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
>           2. Use an 'int' return type on '__pyx_fuse_0_scal' to allow an error code to be returned.
>       multiprocessing.pool.RemoteTraceback:
>       """
>       Traceback (most recent call last):
>         File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
>           result = (True, func(*args, **kwds))
>                           ^^^^^^^^^^^^^^^^^^^
>         File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
>           return list(map(*args))
>                  ^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1345, in cythonize_one_helper
>           return cythonize_one(*m)
>                  ^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
>           raise CompileError(None, pyx_file)
>       Cython.Compiler.Errors.CompileError: sklearn/ensemble/_hist_gradient_boosting/splitting.pyx
>       """
>       
>       The above exception was the direct cause of the following exception:
>       
>       Traceback (most recent call last):
>         File "/Users/jkhartshorne/Documents/Projects/FormosanBank/new_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>       [ 1/59] Cythonizing sklearn/__check_build/_check_build.pyx
>       [ 2/59] Cythonizing sklearn/_isotonic.pyx
>       [ 3/59] Cythonizing sklearn/_loss/_loss.pyx
>       [ 4/59] Cythonizing sklearn/cluster/_dbscan_inner.pyx
>       [ 5/59] Cythonizing sklearn/cluster/_hierarchical_fast.pyx
>       [ 6/59] Cythonizing sklearn/cluster/_k_means_common.pyx
>       [ 7/59] Cythonizing sklearn/cluster/_k_means_elkan.pyx
>       [ 8/59] Cythonizing sklearn/cluster/_k_means_lloyd.pyx
>       [ 9/59] Cythonizing sklearn/cluster/_k_means_minibatch.pyx
>       [10/59] Cythonizing sklearn/datasets/_svmlight_format_fast.pyx
>       [11/59] Cythonizing sklearn/decomposition/_cdnmf_fast.pyx
>       [12/59] Cythonizing sklearn/decomposition/_online_lda_fast.pyx
>       [13/59] Cythonizing sklearn/ensemble/_gradient_boosting.pyx
>       [14/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_binning.pyx
>       [15/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_bitset.pyx
>       [16/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_gradient_boosting.pyx
>       [17/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/_predictor.pyx
>       [18/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/common.pyx
>       [19/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/histogram.pyx
>       [20/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/splitting.pyx
>       [21/59] Cythonizing sklearn/ensemble/_hist_gradient_boosting/utils.pyx
>       [22/59] Cythonizing sklearn/feature_extraction/_hashing_fast.pyx
>       [23/59] Cythonizing sklearn/linear_model/_cd_fast.pyx
>       [24/59] Cythonizing sklearn/linear_model/_sag_fast.pyx
>       [25/59] Cythonizing sklearn/linear_model/_sgd_fast.pyx
>       [26/59] Cythonizing sklearn/manifold/_barnes_hut_tsne.pyx
>       [27/59] Cythonizing sklearn/manifold/_utils.pyx
>       [28/59] Cythonizing sklearn/metrics/_dist_metrics.pyx
>       [29/59] Cythonizing sklearn/metrics/_pairwise_distances_reduction.pyx
>       [30/59] Cythonizing sklearn/metrics/_pairwise_fast.pyx
>       [31/59] Cythonizing sklearn/metrics/cluster/_expected_mutual_info_fast.pyx
>       [32/59] Cythonizing sklearn/neighbors/_ball_tree.pyx
>       [33/59] Cythonizing sklearn/neighbors/_kd_tree.pyx
>       [34/59] Cythonizing sklearn/neighbors/_partition_nodes.pyx
>       [35/59] Cythonizing sklearn/neighbors/_quad_tree.pyx
>       [36/59] Cythonizing sklearn/preprocessing/_csr_polynomial_expansion.pyx
>       [37/59] Cythonizing sklearn/svm/_liblinear.pyx
>       [38/59] Cythonizing sklearn/svm/_libsvm.pyx
>       [39/59] Cythonizing sklearn/svm/_libsvm_sparse.pyx
>       [40/59] Cythonizing sklearn/svm/_newrand.pyx
>       [41/59] Cythonizing sklearn/tree/_criterion.pyx
>       [42/59] Cythonizing sklearn/tree/_splitter.pyx
>       [43/59] Cythonizing sklearn/tree/_tree.pyx
>       [44/59] Cythonizing sklearn/tree/_utils.pyx
>       [45/59] Cythonizing sklearn/utils/_cython_blas.pyx
>       [46/59] Cythonizing sklearn/utils/_fast_dict.pyx
>       [47/59] Cythonizing sklearn/utils/_heap.pyx
>       [48/59] Cythonizing sklearn/utils/_logistic_sigmoid.pyx
>       [49/59] Cythonizing sklearn/utils/_openmp_helpers.pyx
>       [50/59] Cythonizing sklearn/utils/_random.pyx
>       [51/59] Cythonizing sklearn/utils/_readonly_array_wrapper.pyx
>       [52/59] Cythonizing sklearn/utils/_seq_dataset.pyx
>       [53/59] Cythonizing sklearn/utils/_sorting.pyx
>       [54/59] Cythonizing sklearn/utils/_typedefs.pyx
>       [55/59] Cythonizing sklearn/utils/_vector_sentinel.pyx
>       [56/59] Cythonizing sklearn/utils/_weight_vector.pyx
>       [57/59] Cythonizing sklearn/utils/arrayfuncs.pyx
>       [58/59] Cythonizing sklearn/utils/murmurhash.pyx
>       [59/59] Cythonizing sklearn/utils/sparsefuncs_fast.pyx
>           main()
>         File "/Users/jkhartshorne/Documents/Projects/FormosanBank/new_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/Users/jkhartshorne/Documents/Projects/FormosanBank/new_env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
>           return hook(metadata_directory, config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
>           self.run_setup()
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
>           self).run_setup(setup_script=setup_script)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
>           exec(compile(code, __file__, 'exec'), locals())
>         File "setup.py", line 328, in <module>
>           setup_package()
>         File "setup.py", line 324, in setup_package
>           setup(**metadata)
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/numpy/distutils/core.py", line 135, in setup
>           config = configuration()
>                    ^^^^^^^^^^^^^^^
>         File "setup.py", line 187, in configuration
>           config.add_subpackage("sklearn")
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/numpy/distutils/misc_util.py", line 1050, in add_subpackage
>           config_list = self.get_subpackage(subpackage_name, subpackage_path,
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/numpy/distutils/misc_util.py", line 1016, in get_subpackage
>           config = self._get_configuration_from_setup_py(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/numpy/distutils/misc_util.py", line 958, in _get_configuration_from_setup_py
>           config = setup_module.configuration(*args)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-install-csa7usi2/scikit-learn_ee750f91af574777b8a352e035c58ac5/sklearn/setup.py", line 85, in configuration
>           cythonize_extensions(top_path, config)
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-install-csa7usi2/scikit-learn_ee750f91af574777b8a352e035c58ac5/sklearn/_build_utils/__init__.py", line 74, in cythonize_extensions
>           config.ext_modules = cythonize(
>                                ^^^^^^^^^^
>         File "/private/var/folders/r0/hwz_y7sd2z3d2289s5jmtv180000gp/T/pip-build-env-nq40i7q6/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1145, in cythonize
>           result.get(99999)  # seconds
>           ^^^^^^^^^^^^^^^^^
>         File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
>           raise self._value
>       Cython.Compiler.Errors.CompileError: sklearn/ensemble/_hist_gradient_boosting/splitting.pyx
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> [notice] A new release of pip is available: 24.2 -> 24.3.1
> [notice] To update, run: pip install --upgrade pip
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**Comment by jkhartshorne** [comment]
Some of the specified versions are very old. What I'm finding suggests there may be incompatibilities between them and perhaps between them and more recent versions of python 3.

**Comment by jkhartshorne** [comment]
For the moment, I've gotten around this by installing the latest versions of the required libraries. And also setuptools, which isn't in requirements.txt but seems to be required.

However, that results in a problem with Matplotlib:

> (.venv) jkhartshorne@MacBook-Air-345 FormosanBank % python QC/orthography/orthography_extract.py --language Amis --corpus All --corpora_path ./Corpora
> Traceback (most recent call last):
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/QC/orthography/orthography_extract.py", line 424, in <module>
>     main(args, langs)
>     ~~~~^^^^^^^^^^^^^
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/QC/orthography/orthography_extract.py", line 395, in main
>     visualize(o_info, output_folder)
>     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/QC/orthography/orthography_extract.py", line 183, in visualize
>     plt.figure(figsize=(12, 6))
>     ~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/pyplot.py", line 1027, in figure
>     manager = new_figure_manager(
>         num, figsize=figsize, dpi=dpi,
>         facecolor=facecolor, edgecolor=edgecolor, frameon=frameon,
>         FigureClass=FigureClass, **kwargs)
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/pyplot.py", line 549, in new_figure_manager
>     _warn_if_gui_out_of_main_thread()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/pyplot.py", line 526, in _warn_if_gui_out_of_main_thread
>     canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
>                                                 ~~~~~~~~~~~~~~~~^^
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/pyplot.py", line 358, in _get_backend_mod
>     switch_backend(rcParams._get("backend"))
>     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/pyplot.py", line 415, in switch_backend
>     module = backend_registry.load_backend_module(newbackend)
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/backends/registry.py", line 323, in load_backend_module
>     return importlib.import_module(module_name)
>            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
>     from . import _backend_tk
>   File "/Users/jkhartshorne/Documents/Projects/FormosanBank/.venv/lib/python3.13/site-packages/matplotlib/backends/_backend_tk.py", line 25, in <module>
>     from . import _tkagg
> ImportError: Failed to load Tcl_SetVar

**Comment by wmohamed24** [comment]
Should be fixed. I was using pipreqs to generate the requirements.txt because it only includes the imported library which is nicer than pip freeze (which includes everything in the env), but apparently pipreqs doesn't work very well. I tried creating a new environment, installing the requirements.txt and ran the script and everything ran fine
