### ISSUE TITLE
Allow selection of specific corpus for testing

### ISSUE THREAD

**Issue by jkhartshorne** [FormosanBank/FormosanBank#6]
It's nice to be able to check all corpora simultaneously. But eventually we'll be adding individual new corpora. And it can take time to run tests on all the corpora -- which is a little unnecessary if they haven't changed.

Suggest you add a flag that allows you to specify a path to a specific corpus.

For now, this should be added to punct_check.py and validate_xml.py and orthography_extract.py.

**Comment by AI4CommSci** [comment]
I added a detailed breakdown of the modifications to validate_xml as a comment to the other issue. I have done similar work with the orthography_extract.py. Now user will need to specify the language and corpus as command line argument. I'm working on writing a readme for instructions about how to use. 

So, only punct_check.py is left so far!

**Comment by hunterschep** [comment]
Working on implementing this in the punctuation check now

**Comment by hunterschep** [comment]
in validate punct you can now specify a corpus!
