### ISSUE TITLE
Have punct_check.py indicate whether a corpus "passed"

### ISSUE THREAD

**Issue by jkhartshorne** [FormosanBank/FormosanBank#8]
Will need to address https://github.com/FormosanBank/FormosanBank/issues/7 first.

I think the output that you have is great. But ultimately, the workflow will be easier if the code returns "PASS" or "FAIL". So we can define what constitutes a PASS.

We don't want any smart quotes (single or double). We don't want any unmatched quotes. And so on. 

The PASS/FAIL could be returned separately for each corpus.

**Comment by hunterschep** [comment]
@jkhartshorne closing this issue as my latest commit addresses this 

Corpuses now print a pass if they pass and a fail if they fail 

If they fail, it prints out the reasons that failed
